name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 7 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.4.x
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x
    - name: Build and test with Rake
      run: rake
